SET DEFINE OFF;
Insert into REALDB.DESCRIPCION_VIVIENDAS
   (ID_DESCR_VIVIENDA, CANT_BANOS, CANT_HABITACIONES, CANT_PISOS, UBICACION_PISO, 
    GARAJE, GAS, ENERGIA, AGUA, DIRECCION)
 Values
   (1, 2, 3, 5, '2', 
    1, 1, 1, 1, 'CALLE 13 # 11-15');
Insert into REALDB.DESCRIPCION_VIVIENDAS
   (ID_DESCR_VIVIENDA, CANT_BANOS, CANT_HABITACIONES, CANT_PISOS, UBICACION_PISO, 
    GARAJE, GAS, ENERGIA, AGUA, DIRECCION)
 Values
   (2, 4, 5, 3, '1,2,3', 
    1, 1, 1, 1, 'CALLE 21 # 14-33');
COMMIT;
