SET DEFINE OFF;
Insert into REALDB.DETALLE_VIVIENDAS
   (ID_DETA_VIVIENDA, ID_DESCR_VIVIENDA, ID_T_VIVIENDA, ID_CONTRATO, PRECIO)
 Values
   (1, 1, 1, 1, 1000000);
Insert into REALDB.DETALLE_VIVIENDAS
   (ID_DETA_VIVIENDA, ID_DESCR_VIVIENDA, ID_T_VIVIENDA, ID_CONTRATO, PRECIO)
 Values
   (2, 2, 2, 2, 123000000);
COMMIT;
