SET DEFINE OFF;
Insert into REALDB.TIPO_VIVIENDAS
   (ID_T_VIVIENDA, DESCRI_V)
 Values
   (1, 'CASA');
Insert into REALDB.TIPO_VIVIENDAS
   (ID_T_VIVIENDA, DESCRI_V)
 Values
   (2, 'APARTAMENTO');
Insert into REALDB.TIPO_VIVIENDAS
   (ID_T_VIVIENDA, DESCRI_V)
 Values
   (3, 'FINCA');
COMMIT;
