SET DEFINE OFF;
Insert into REALDB.TIPO_CONTRATOS
   (ID_CONTRATO, DESCRI_C)
 Values
   (1, 'ARRIENDO');
Insert into REALDB.TIPO_CONTRATOS
   (ID_CONTRATO, DESCRI_C)
 Values
   (2, 'VENTA');
COMMIT;
