SET DEFINE OFF;
Insert into REALDB.CONSULTA_VIVIENDAS
   (ID_CONSULTA, ID_DETA_VIVIENDA, ID_USER, CLI_USER)
 Values
   (1, 2, 14637425, 1);
Insert into REALDB.CONSULTA_VIVIENDAS
   (ID_CONSULTA, ID_DETA_VIVIENDA, ID_USER, CLI_USER)
 Values
   (2, 1, 77180615, 1);
COMMIT;
